probeTimeoutSeconds: 5
gitlabUrl: http://gitlab.khaolakonline.com/
runnerToken: "glrt-vxGrMxJNSM-prEwtgQSH"
unregisterRunners: true
terminationGracePeriodSeconds: 3600
concurrent: 5
shutdown_timeout: 0
checkInterval: 30
logFormat: json
rbac:
  create: true
  rules: 
    - apiGroups: [""]
      resources: ["configmaps", "events", "pods", "pods/attach", "pods/exec", "secrets", "services"]
      verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "alpine"
        privileged = true
        [[runners.kubernetes.host_aliases]]
          ip = "10.111.0.121"
          hostnames = ["gitlab.thaibevapp.com", "registry.thaibevapp.com", "kas.thaibevapp.com"]
        [[runners.kubernetes.volumes.host_path]]
          name = "docker"
          mount_path = "/var/run/docker.sock"
          read_only = true
          host_path = "/var/run/docker.sock"
certsSecretName: gitlab-cert
serviceAccount:
  create: true
securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  privileged: true
  capabilities:
    drop: ["ALL"]
